// Copies the fonts and PDF library from node_modules into vendor/, so the
// website and the Android app work without reaching a CDN.
// Usage: npm install && npm run vendor
import fs from 'fs';
import path from 'path';

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const out = path.join(root, 'vendor');
const nm = p => path.join(root, 'node_modules', p);
fs.rmSync(out, {recursive: true, force: true});
fs.mkdirSync(path.join(out, 'fonts'), {recursive: true});

fs.copyFileSync(nm('jspdf/dist/jspdf.umd.min.js'), path.join(out, 'jspdf.umd.min.js'));
fs.copyFileSync(nm('jspdf/LICENSE'), path.join(out, 'jspdf-LICENSE.txt'));

// Latin and Latin Extended subsets of the variable fonts (weight + optical size),
// declared under the same family names the stylesheet already uses.
const fonts = [
  ['Bricolage Grotesque', '@fontsource-variable/bricolage-grotesque', 'bricolage-grotesque', '200 800'],
  ['Literata', '@fontsource-variable/literata', 'literata', '200 900'],
];
const ranges = {
  'latin-ext': 'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  latin: 'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
};
let css = '/* Generated by tools/vendor.mjs from @fontsource-variable (SIL Open Font License). */\n';
for (const [family, pkg, base, weight] of fonts) {
  fs.copyFileSync(nm(`${pkg}/LICENSE`), path.join(out, 'fonts', `${base}-OFL.txt`));
  for (const [subset, range] of Object.entries(ranges)) {
    const file = `${base}-${subset}-opsz-normal.woff2`;
    fs.copyFileSync(nm(`${pkg}/files/${file}`), path.join(out, 'fonts', file));
    css += `@font-face{font-family:'${family}';font-style:normal;font-display:swap;font-weight:${weight};` +
      `src:url(fonts/${file}) format('woff2');unicode-range:${range}}\n`;
  }
}
fs.writeFileSync(path.join(out, 'fonts.css'), css);
console.log('Wrote vendor/ (' + fs.readdirSync(path.join(out, 'fonts')).filter(f => f.endsWith('.woff2')).length + ' fonts, jsPDF)');
